# https://peps.python.org/pep-0517/
[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

# https://hatch.pypa.io/latest/config/metadata/
[tool.hatch.version]
source = "vcs"

# read more about configuring hatch at:
# https://hatch.pypa.io/latest/config/build/
[tool.hatch.build.targets.wheel]
packages = ["src/fractal_nd2_converters"]

[tool.hatch.build.targets.sdist]
exclude = [
    "tests",
    "docs",
    "data",
    "examples",
    "notebooks",
    ".github",
    "**/*.ipynb_checkpoints",
    "**/*.ipynb",
]


# Project metadata (see https://peps.python.org/pep-0621)
[project]
name = "fractal-nd2-converters"
dynamic = ["version"]
description = "A collection of fractal tasks to convert Nikon ND2 files to OME-Zarr"
readme = "README.md"
license = { text = "BSD-3-Clause" }
authors = [{ name = "Flurin Sturzenegger", email = "st.flurin@gmail.com" }]
requires-python = ">=3.11,<3.15"

dependencies = [
    "ome-zarr-converters-tools>=0.10.4,<0.11.0",
    "fractal-task-tools>=0.5.0,<0.6.0",
    "fsspec",
    "nd2",
    "xarray",
]

# Optional dependencies (e.g. for `pip install -e ".[dev]"`, see
# https://peps.python.org/pep-0621/#dependencies-optional-dependencies)
[project.optional-dependencies]
dev = [
    "plotly",
    "notebook",
    "matplotlib",
    "devtools",
    "hatch",
    "pytest",
    "pytest-cov",
    "requests",
    "jsonschema",
    "ruff",
    "ty",
    "pre-commit",
]
test = ["pytest", "pytest-cov", "jsonschema", "requests"]
docs = ["mkdocs-material", "mike"]

# https://docs.astral.sh/ruff
[tool.ruff]
line-length = 88
target-version = "py311"
src = ["src"]

# https://docs.astral.sh/ruff/rules
[tool.ruff.lint]
pydocstyle = { convention = "google" }
select = [
    "E",    # style errors
    "W",    # style warnings
    "F",    # flakes
    "D",    # pydocstyle
    "D417", # Missing argument descriptions in Docstrings
    "I",    # isort
    "UP",   # pyupgrade
    "C4",   # flake8-comprehensions
    "B",    # flake8-bugbear
    "A001", # flake8-builtins
    "RUF",  # ruff-specific rules
    "TC",   # flake8-type-checking
    "TID",  # flake8-tidy-imports
]
ignore = [
    "D401", # First line should be in imperative mood (remove to opt in)
    "D415", # First line should end with a period (remove to opt in)
]

[tool.ruff.lint.per-file-ignores]
"tests/*.py" = ["D", "S"]

# https://docs.astral.sh/ruff/formatter/
[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 89
skip-magic-trailing-comma = false # default is false

[tool.ty.environment]
python = ".pixi/envs/dev"


[tool.pytest.ini_options]
minversion = "8.0"
testpaths = ["tests"]
addopts = [
    "--color=yes",
    "--cov",
    "--cov-report=term-missing",
    "--cov-report=xml",
]

[tool.coverage.run]
source = ["fractal_nd2_converters"]

[tool.coverage.report]
show_missing = true
exclude_lines = [
    "pragma: no cover",
    "if TYPE_CHECKING:",
    "@overload",
    "except ImportError",
    "\\.\\.\\.",
    "raise NotImplementedError()",
    "pass",
]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["win-64", "osx-arm64", "linux-64"]

[tool.pixi.pypi-dependencies]
fractal-nd2-converters = { path = ".", editable = true }
# For local development, you can use the following line instead of the one above
# ome-zarr-converters-tools = { path = "../ome-zarr-converters-tools", editable = true }
# ngio = { path = "../ngio", editable = true }

[tool.pixi.environments]
default = { solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }
test = { features = ["test"], solve-group = "default" }
docs = { features = ["docs"], solve-group = "default" }

[tool.pixi.feature.dev.tasks]
ruff-fix-imports = { cmd = "ruff check --select I --fix" }
ruff = { cmd = "ruff format", depends-on = ["ruff-fix-imports"] }
test = { cmd = "pytest", depends-on = ["ruff"] }
chores = { cmd = "pre-commit run --all-files", depends-on = ["test"] }
